apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp-container
          image: pankajexpressian/nodeapp3:1
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nodeapp
  ports:
    - port: 3333
      targetPort: 3333
