apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  # property-like keys; each key maps to a simple value
  mysecret.username: "VGhpcyBpcyB1c2VyIG5hbWU="
  mysecret.password: "dGhpcyBpcyBwYXNzd29yZA=="
